name: Basic Github Actions YAML
on: 
  push:

jobs:
  testing:
    name: Testing files
    runs on: ubuntu-latest
    steps:
      - name: listing the files
        run: ls
      - name: Read the files
        run: cat index.html