name: Basic Github Actions YAML
on: 
  push:

jobs:
  testing:
    name: Testing files
    runs-on: ubuntu-latest
    steps:
      - name: Reading repo files using Actions
        uses: actions/checkout@v4
      - name: listing the files
        run: ls
      - name: Read the files
        run: cat index.html