name: Exploring variables and secrets
on:
  push:
env:
  CONTAINER_REGISTRY: docker.io
  IMAGE_NAME: github-actions-nginx

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: variable and secret repository
        run: echo docker build -t ${{ env.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME
      
      - run: echo docker login --username=${{ vars.DOCKER_USERNAME }} --password= ${{ secrets.DOCKER_PASSWORD }} 

  deploy:
  needs: docker
    runs-on: ubuntu-latest
    concurrency: 
      cancel-in-progress: true
      group: vaishnavi
    steps:
    - name: running CONTAINER
      run: |
      echo docker run -itd -p 8080:80 $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }} / $IMAGE_NAME
      sleep 600