name: Exploring Matrix
on:
  push:

jobs:
  testing:
    strategy:
      matrix:
        os: [ubuntu-latest , windows-latest , ubuntu-22.04]
        image: [hello-world , debian]
        exclude:
        - os: windows-latest
          image: debian
      max-parallel: 3
    runs-on: "${{ matrix.os}}"
    steps:
      - run: docker run  ${{ matrix.image }}